### ISSUE TITLE
pip install error: No such file or directory: 'VERSION'

### ISSUE THREAD

**Issue by SuperOok** [mmabey/vbox-sdk#3]
Running 'python -m pip install vbox_sdk' results in 

```
Collecting vbox-sdk
  Downloading https://files.pythonhosted.org/packages/2d/ee/e14414b50222afcf644b98e436da3563241bc2fce445474e38265fe74487/vbox_sdk-5.1.18-0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Schnoor\AppData\Local\Temp\pip-install-83dgz3tt\vbox-sdk\setup.py", line 7, in <module>
        with open('VERSION') as v_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
```

The archive mentioned above has a setup.py which states

```
with open('VERSION') as v_file:
    version = v_file.read().strip()
```

The archive contains no file named VERSION. Seems the packaging mechanism somehow loses the file?

**Comment by mmabey** [comment]
Thanks for reporting this. I'll look into it and see if I can tell what's going on.

Can you tell me more about the environment you're working in? Operating system (looks like Win 7+)? Version of Python? Version of pip?

**Comment by SuperOok** [comment]
I'm using Windows 10, Python 3.6, pip 10.0.1

My workaround was to unpack the archive in a local dir and edit the corresponding setup.py such that it does not require the VERSION file. As such, the library works fine in my context.

**Comment by Panthera-uncia-uncioides** [comment]
Hey, guess I got the same error:

Downloading https://files.pythonhosted.org/packages/2d/ee/e14414b50222afcf644b98e436da3563241bc2fce445474e38265fe74487/vbox_sdk-5.1.18-0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-62x20vqd/vbox-sdk/setup.py", line 7, in <module>
        with open('VERSION') as v_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-62x20vqd/vbox-sdk/


using openSUSE, Python 3.6, pip 19.1.1


Thanks 4 fixing this :)

**Comment by Harveyhase68** [comment]
Hello, I have the same problem, Windows 10 Pro 64bit:

pip install vbox_sdk
Collecting vbox_sdk
  Using cached vbox_sdk-5.1.18-0.tar.gz (33 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-mdlnin01\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-mdlnin01\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-mdlnin01\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-mdlnin01\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\Users\user\Qsync\Python_Temp\Python3>pip --version
pip 24.3.1 from C:\Program Files\Python312\Lib\site-packages\pip (python 3.12)

**Comment by Quasar9000** [comment]
I am also getting this "VERSION" error.
```
OS = Win10
Python = 3.13.2
PIP = 25.0.1
```
